### ISSUE TITLE
ConditionListTest does not use equals

### ISSUE THREAD

**Issue by wcomhelp** [CMPUT301F18T28/Personal-Condition-Tracker#34]
The tests in ConditionListTest use == rather than .equals(). This will cause unintended behavior.
testAdd_SearchCondition - line 35 - should use assertEquals() instead.
testDeleteCondition - line 48 - should use assertEquals() instead.

**Comment by douziech** [comment]
testAdd_SearchCondition()  uses '==' because it's actually testing that the object returned has the same location in memory as the original; therefore it has located the same object which is the purpose of the search.  The other test that uses  '==' is for length of the array, which is an integer (primitive), so it should be fine too.  The rest of the cases use .equals().
